trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - assets/demo-3-deployment
    - .devops/pipelines/qa.yml
    exclude:
    - README.md

variables:
  location: West Europe

# Use build definition name for build/release numbers
name: $(BuildDefinitionName).$(Year:yy)$(DayOfYear)$(rev:.r)

stages:
- stage: Validation
  jobs:
  - job: Validate
    displayName: Validate ARM Templates
    continueOnError: false
    pool:
      name: 'Azure pipelines'
      vmImage: windows-2019
    workspace:
      clean: all
    steps:
    - task: RunARMTTKTests@1
      inputs:
        templatelocation: '$(System.DefaultWorkingDirectory)\assets\demo-3-deployment'
        resultLocation: '$(System.DefaultWorkingDirectory)\results'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'NUnit'
        testResultsFiles: '$(System.DefaultWorkingDirectory)\results\*-armttk.xml'
      condition: always()

    - task: AzureResourceGroupDeployment@2
      name: Validate_ARM_Templates
      inputs:
        azureSubscription: Visual Studio Enterprise
        action: 'Create Or Update Resource Group'
        resourceGroupName: rg-arm-in-a-serverless-world
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: assets/demo-3-deployment/azuredeploy.json
        deploymentMode: 'Validation'
      condition: always()

    - publish: assets/demo-3-deployment
      displayName: 'Publish Artifacts'
      artifact: demo-3-deployment
      dependsOn: Validate_ARM_Templates
      condition: succeeded()

- stage: Deployment 
  dependsOn: Validation
  condition: succeeded()
  jobs:
  - deployment: 
    environment: Production
    continueOnError: false
    pool:
      name: 'Azure pipelines'
      vmImage: windows-2019
    workspace:
      clean: all
    strategy: 
      runOnce:
        deploy:
          steps:  
          - task: AzureResourceGroupDeployment@2
            name: Deploy_ARM_Templates
            inputs:
              azureSubscription: Visual Studio Enterprise
              action: 'Create Or Update Resource Group'
              resourceGroupName: rg-arm-in-a-serverless-world
              location: $(location)
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)/demo-3-deployment/azuredeploy.json'
              deploymentMode: 'Incremental'